version: '2.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      HISTFILE: '/root/.bashhistory/.bash_history'
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: SO9KNO6YT9OGE39PQCZW
      MINIO_SECRET_KEY: EzH5iGs3qbJr1MwIMf2AUyfqzewgd2qgrk9+i+vU
      MINIO_BUCKET_NAME: imagedetection
    volumes:
      - .:/opt/project/app
      - bash-history:/root/.bashhistory
      - $HOME/.ssh:/root/.ssh
    working_dir: /opt/project/app

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1; do :; done"

volumes:
  bash-history:
